// Operator roster with colors and roles
const OPERATORS = {
  Rico:    { color: '#e74c3c', role: 'Team Leader' },
  Chris:   { color: '#3498db', role: 'Point — Left Entry' },
  Mags:    { color: '#2ecc71', role: 'Point — Right Entry (Button Hook)' },
  Manny:   { color: '#f39c12', role: 'Hallway Point' },
  Mike:    { color: '#9b59b6', role: 'Family Room' },
  Ian:     { color: '#1abc9c', role: 'Family Room Support' },
  Austin:  { color: '#e67e22', role: 'Kitchen / Last Room' },
  Ashley:  { color: '#e91e8c', role: 'Kitchen Lead' },
  Dylan:   { color: '#00bcd4', role: 'Trailer / Bathroom' },
  Cassidy: { color: '#cddc39', role: 'Hallway Support / Room 1' },
};

// Floor plan geometry (canvas coords, 360×480)
// Origin: top-left. Front door on left wall ~y:200.
const ROOMS = {
  living: { x: 10,  y: 10,  w: 160, h: 200, label: 'Living\nRoom' },
  family: { x: 190, y: 10,  w: 160, h: 200, label: 'Family\nRoom' },
  hall:   { x: 10,  y: 220, w: 340, h: 60,  label: 'Hallway' },
  kitchen:{ x: 190, y: 295, w: 160, h: 110, label: 'Kitchen' },
  bath:   { x: 190, y: 415, w: 160, h: 55,  label: 'Bathroom' },
  room1:  { x: 10,  y: 295, w: 90,  h: 80,  label: 'Room 1\n(closed R)' },
  room2:  { x: 10,  y: 385, w: 90,  h: 80,  label: 'Room 2\n(closed L)' },
  last:   { x: 10,  y: 415, w: 90,  h: 55,  label: 'Last Room\n(open L)' },
};

// Door locations: { x, y, side } — side = N/S/E/W wall
const DOORS = {
  front:   { x: 10,  y: 105, side: 'W', label: 'FRONT DOOR' },
  hallFam: { x: 185, y: 240, side: 'E', label: '' }, // hall→family rm pass
  kitchen: { x: 265, y: 290, side: 'N', label: '' },
  bath:    { x: 265, y: 410, side: 'N', label: '' },
  room1:   { x: 105, y: 290, side: 'N', label: 'Closed R' },
  room2:   { x: 55,  y: 380, side: 'S', label: 'Closed L' },
  last:    { x: 55,  y: 410, side: 'N', label: 'Open L' },
};

// Each step: { title, callout, teaching, positions: { name: {x,y,angle,room} }, angles: [...], event }
// angle in degrees (0=right, 90=down). positions keyed by operator name.
// event: 'breach'|'bang'|'entry'|'clear' for visual fx
const STEPS = [
  // 1
  {
    title: 'Stack at front door',
    callout: '',
    teaching: 'Full stack staged outside. Rico is rear command. Chris leads, Mags second.',
    positions: {
      Rico:    { x: -30, y: 100 },
      Chris:   { x: -20, y: 90  },
      Mags:    { x: -20, y: 115 },
      Manny:   { x: -20, y: 130 },
      Mike:    { x: -20, y: 145 },
      Ian:     { x: -20, y: 160 },
      Austin:  { x: -20, y: 175 },
      Ashley:  { x: -20, y: 190 },
      Dylan:   { x: -20, y: 205 },
      Cassidy: { x: -20, y: 220 },
    },
    angles: [],
    event: null,
  },
  // 2
  {
    title: 'Rico: Initiate',
    callout: 'Rico: "Initiate."',
    teaching: 'The command to initiate is Rico\'s call only. No one moves before this.',
    positions: {
      Rico:    { x: -30, y: 100 },
      Chris:   { x: -20, y: 90  },
      Mags:    { x: -20, y: 115 },
      Manny:   { x: -20, y: 130 },
      Mike:    { x: -20, y: 145 },
      Ian:     { x: -20, y: 160 },
      Austin:  { x: -20, y: 175 },
      Ashley:  { x: -20, y: 190 },
      Dylan:   { x: -20, y: 205 },
      Cassidy: { x: -20, y: 220 },
    },
    angles: [],
    event: null,
  },
  // 3
  {
    title: 'Explosive breach',
    callout: '— BREACH —',
    teaching: 'Explosive breach opens the front door. Stack prepares to flow.',
    positions: {
      Rico:    { x: -30, y: 100 },
      Chris:   { x: -10, y: 90  },
      Mags:    { x: -10, y: 115 },
      Manny:   { x: -20, y: 130 },
      Mike:    { x: -20, y: 145 },
      Ian:     { x: -20, y: 160 },
      Austin:  { x: -20, y: 175 },
      Ashley:  { x: -20, y: 190 },
      Dylan:   { x: -20, y: 205 },
      Cassidy: { x: -20, y: 220 },
    },
    angles: [],
    event: 'breach',
  },
  // 4
  {
    title: 'Chris enters — limited penetration',
    callout: '',
    teaching: 'Chris enters from the left side of the door with limited penetration. He clears deep corners first, then shifts gaze toward center.',
    positions: {
      Rico:    { x: -30, y: 100 },
      Chris:   { x: 45,  y: 80  },
      Mags:    { x: -10, y: 115 },
      Manny:   { x: -20, y: 130 },
      Mike:    { x: -20, y: 145 },
      Ian:     { x: -20, y: 160 },
      Austin:  { x: -20, y: 175 },
      Ashley:  { x: -20, y: 190 },
      Dylan:   { x: -20, y: 205 },
      Cassidy: { x: -20, y: 220 },
    },
    angles: [{ op: 'Chris', x: 45, y: 80, deg: 60 }],
    event: 'entry',
  },
  // 5
  {
    title: 'Mags enters — button hook',
    callout: '',
    teaching: 'Mags follows and button hooks to the right. Both hold with enough room for the rest of the stack to enter.',
    positions: {
      Rico:    { x: -30, y: 100 },
      Chris:   { x: 45,  y: 80  },
      Mags:    { x: 45,  y: 130 },
      Manny:   { x: -20, y: 130 },
      Mike:    { x: -20, y: 145 },
      Ian:     { x: -20, y: 160 },
      Austin:  { x: -20, y: 175 },
      Ashley:  { x: -20, y: 190 },
      Dylan:   { x: -20, y: 205 },
      Cassidy: { x: -20, y: 220 },
    },
    angles: [
      { op: 'Chris', x: 45, y: 80,  deg: 60  },
      { op: 'Mags',  x: 45, y: 130, deg: 120 },
    ],
    event: 'entry',
    note: 'They hold position with enough room for the rest of the stack to enter.',
  },
  // 6
  {
    title: 'Stack flows in',
    callout: '',
    teaching: 'Manny, Mike, Ian, Austin, Ashley, Dylan, and Cassidy flow through the door. Rico enters last.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 45,  y: 80  },
      Mags:    { x: 45,  y: 130 },
      Manny:   { x: 60,  y: 100 },
      Mike:    { x: 75,  y: 100 },
      Ian:     { x: 90,  y: 100 },
      Austin:  { x: 105, y: 100 },
      Ashley:  { x: 120, y: 100 },
      Dylan:   { x: 135, y: 100 },
      Cassidy: { x: 150, y: 100 },
    },
    angles: [
      { op: 'Chris', x: 45, y: 80,  deg: 60  },
      { op: 'Mags',  x: 45, y: 130, deg: 120 },
    ],
    event: null,
  },
  // 7
  {
    title: 'Chris and Mags shift angles',
    callout: '',
    teaching: 'Chris shifts forward and angles toward the family room opening. Mags angles toward the hallway opening — safe passage for Manny and Mike.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 70,  y: 100 },
      Mike:    { x: 85,  y: 100 },
      Ian:     { x: 100, y: 100 },
      Austin:  { x: 115, y: 100 },
      Ashley:  { x: 130, y: 100 },
      Dylan:   { x: 145, y: 100 },
      Cassidy: { x: 155, y: 100 },
    },
    angles: [
      { op: 'Chris', x: 55, y: 75,  deg: 30  },
      { op: 'Mags',  x: 55, y: 135, deg: 150 },
    ],
    event: null,
  },
  // 8
  {
    title: 'Manny calls hallway point',
    callout: 'Manny: "Hallway right, Manny on point."',
    teaching: 'Manny identifies the hallway and claims point. This is the first hallway callout — name included.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 95,  y: 160 },
      Mike:    { x: 85,  y: 100 },
      Ian:     { x: 100, y: 100 },
      Austin:  { x: 115, y: 100 },
      Ashley:  { x: 130, y: 100 },
      Dylan:   { x: 145, y: 100 },
      Cassidy: { x: 155, y: 100 },
    },
    angles: [
      { op: 'Chris', x: 55, y: 75,  deg: 30  },
      { op: 'Mags',  x: 55, y: 135, deg: 150 },
      { op: 'Manny', x: 95, y: 160, deg: 90  },
    ],
    event: null,
  },
  // 9
  {
    title: 'Mike posts on family room',
    callout: '',
    teaching: 'Mike moves up and posts on the family room entry. Ian moves behind Mike.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 95,  y: 160 },
      Mike:    { x: 175, y: 100 },
      Ian:     { x: 155, y: 100 },
      Austin:  { x: 115, y: 100 },
      Ashley:  { x: 130, y: 100 },
      Dylan:   { x: 145, y: 100 },
      Cassidy: { x: 80,  y: 160 },
    },
    angles: [
      { op: 'Chris', x: 55,  y: 75,  deg: 30  },
      { op: 'Mags',  x: 55,  y: 135, deg: 150 },
      { op: 'Manny', x: 95,  y: 160, deg: 90  },
      { op: 'Mike',  x: 175, y: 100, deg: 0   },
    ],
    event: null,
  },
  // 10
  {
    title: 'Ian deploys bang — family room',
    callout: '— BANG — Family Room',
    teaching: 'Ian throws the distraction device into the family room before entry.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 95,  y: 160 },
      Mike:    { x: 175, y: 100 },
      Ian:     { x: 165, y: 100 },
      Austin:  { x: 115, y: 100 },
      Ashley:  { x: 130, y: 100 },
      Dylan:   { x: 145, y: 100 },
      Cassidy: { x: 80,  y: 160 },
    },
    angles: [
      { op: 'Manny', x: 95,  y: 160, deg: 90 },
      { op: 'Mike',  x: 175, y: 100, deg: 0  },
    ],
    event: 'bang',
  },
  // 11
  {
    title: 'Mike and Ian detail family room',
    callout: '',
    teaching: 'Mike enters first; Ian follows. First in = last out. They are responsible for this room.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 95,  y: 160 },
      Mike:    { x: 240, y: 80  },
      Ian:     { x: 270, y: 120 },
      Austin:  { x: 115, y: 100 },
      Ashley:  { x: 130, y: 100 },
      Dylan:   { x: 145, y: 100 },
      Cassidy: { x: 80,  y: 160 },
    },
    angles: [
      { op: 'Manny', x: 95,  y: 160, deg: 90  },
      { op: 'Mike',  x: 240, y: 80,  deg: 45  },
      { op: 'Ian',   x: 270, y: 120, deg: 315 },
    ],
    event: 'entry',
  },
  // 12
  {
    title: 'Austin and Ashley move to kitchen',
    callout: '',
    teaching: 'Austin and Ashley break off toward the kitchen entry.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 95,  y: 160 },
      Mike:    { x: 240, y: 80  },
      Ian:     { x: 270, y: 120 },
      Austin:  { x: 230, y: 255 },
      Ashley:  { x: 250, y: 255 },
      Dylan:   { x: 145, y: 100 },
      Cassidy: { x: 80,  y: 160 },
    },
    angles: [
      { op: 'Manny',  x: 95,  y: 160, deg: 90  },
      { op: 'Austin', x: 230, y: 255, deg: 90  },
      { op: 'Ashley', x: 250, y: 255, deg: 90  },
    ],
    event: null,
  },
  // 13
  {
    title: 'Austin deploys bang — kitchen',
    callout: '— BANG — Kitchen',
    teaching: 'Austin deploys the distraction device before Ashley enters.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 95,  y: 160 },
      Mike:    { x: 240, y: 80  },
      Ian:     { x: 270, y: 120 },
      Austin:  { x: 230, y: 265 },
      Ashley:  { x: 250, y: 265 },
      Dylan:   { x: 145, y: 100 },
      Cassidy: { x: 80,  y: 160 },
    },
    angles: [
      { op: 'Manny',  x: 95,  y: 160, deg: 90 },
    ],
    event: 'bang',
  },
  // 14
  {
    title: 'Ashley enters kitchen first',
    callout: '',
    teaching: 'Ashley enters first, clearing deep right corner. Austin follows and clears left corner.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 95,  y: 160 },
      Mike:    { x: 240, y: 80  },
      Ian:     { x: 270, y: 120 },
      Austin:  { x: 230, y: 330 },
      Ashley:  { x: 300, y: 310 },
      Dylan:   { x: 145, y: 100 },
      Cassidy: { x: 80,  y: 160 },
    },
    angles: [
      { op: 'Manny',  x: 95,  y: 160, deg: 90  },
      { op: 'Ashley', x: 300, y: 310, deg: 45  },
      { op: 'Austin', x: 230, y: 330, deg: 135 },
    ],
    event: 'entry',
  },
  // 15
  {
    title: 'Austin notices bathroom door — calls Trailer',
    callout: 'Austin: "Trailer."',
    teaching: 'Austin spots the closed bathroom door. Dylan is designated Trailer and responds.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 95,  y: 160 },
      Mike:    { x: 240, y: 80  },
      Ian:     { x: 270, y: 120 },
      Austin:  { x: 215, y: 370 },
      Ashley:  { x: 300, y: 310 },
      Dylan:   { x: 145, y: 100 },
      Cassidy: { x: 80,  y: 160 },
    },
    angles: [
      { op: 'Manny',  x: 95,  y: 160, deg: 90  },
      { op: 'Austin', x: 215, y: 370, deg: 180 },
    ],
    event: null,
  },
  // 16
  {
    title: 'Dylan moves to bathroom door',
    callout: '',
    teaching: 'Dylan (Trailer) moves up the hallway and posts on the bathroom door — doorknob side. Austin shifts to hinge side.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 95,  y: 160 },
      Mike:    { x: 240, y: 80  },
      Ian:     { x: 270, y: 120 },
      Austin:  { x: 215, y: 425 },
      Ashley:  { x: 300, y: 310 },
      Dylan:   { x: 275, y: 400 },
      Cassidy: { x: 80,  y: 160 },
    },
    angles: [
      { op: 'Manny', x: 95,  y: 160, deg: 90  },
      { op: 'Dylan', x: 275, y: 400, deg: 180 },
    ],
    event: null,
  },
  // 17
  {
    title: 'Dylan opens and deploys bang — bathroom',
    callout: '— BANG — Bathroom',
    teaching: 'Dylan is on doorknob side. Door opens inward. Dylan opens and throws — Austin enters first.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 95,  y: 160 },
      Mike:    { x: 240, y: 80  },
      Ian:     { x: 270, y: 120 },
      Austin:  { x: 215, y: 425 },
      Ashley:  { x: 300, y: 310 },
      Dylan:   { x: 285, y: 410 },
      Cassidy: { x: 80,  y: 160 },
    },
    angles: [
      { op: 'Manny', x: 95,  y: 160, deg: 90 },
    ],
    event: 'bang',
  },
  // 18
  {
    title: 'Austin and Dylan detail bathroom',
    callout: '',
    teaching: 'Austin enters first. Dylan follows. They detail the bathroom. First in = last out.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 95,  y: 160 },
      Mike:    { x: 240, y: 80  },
      Ian:     { x: 270, y: 120 },
      Austin:  { x: 225, y: 445 },
      Ashley:  { x: 300, y: 310 },
      Dylan:   { x: 300, y: 445 },
      Cassidy: { x: 80,  y: 160 },
    },
    angles: [
      { op: 'Manny',  x: 95,  y: 160, deg: 90  },
      { op: 'Austin', x: 225, y: 445, deg: 225 },
      { op: 'Dylan',  x: 300, y: 445, deg: 315 },
    ],
    event: 'entry',
  },
  // 19
  {
    title: 'Manny calls — Closed door right',
    callout: 'Manny: "Closed door right."',
    teaching: 'Manny bumps past the first closed door on the right. Cassidy moves with him — she sets on the door.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 55,  y: 270 },
      Mike:    { x: 240, y: 80  },
      Ian:     { x: 270, y: 120 },
      Austin:  { x: 225, y: 445 },
      Ashley:  { x: 300, y: 310 },
      Dylan:   { x: 300, y: 445 },
      Cassidy: { x: 70,  y: 270 },
    },
    angles: [
      { op: 'Manny',   x: 55, y: 270, deg: 90 },
      { op: 'Cassidy', x: 70, y: 270, deg: 0  },
    ],
    event: null,
  },
  // 20
  {
    title: 'Cassidy opens — bang — Room 1',
    callout: '— BANG — Room 1',
    teaching: 'Cassidy on doorknob side. Ashley on hinge side. Cassidy opens and deploys bang.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 40,  y: 310 },
      Mike:    { x: 240, y: 80  },
      Ian:     { x: 270, y: 120 },
      Austin:  { x: 225, y: 445 },
      Ashley:  { x: 30,  y: 280 },
      Dylan:   { x: 300, y: 445 },
      Cassidy: { x: 100, y: 280 },
    },
    angles: [
      { op: 'Manny', x: 40, y: 310, deg: 90 },
    ],
    event: 'bang',
  },
  // 21
  {
    title: 'Ashley and Cassidy detail Room 1',
    callout: '',
    teaching: 'Ashley enters first. Cassidy follows. They detail Room 1.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 40,  y: 355 },
      Mike:    { x: 240, y: 80  },
      Ian:     { x: 270, y: 120 },
      Austin:  { x: 225, y: 445 },
      Ashley:  { x: 30,  y: 325 },
      Dylan:   { x: 300, y: 445 },
      Cassidy: { x: 80,  y: 350 },
    },
    angles: [
      { op: 'Manny',   x: 40,  y: 355, deg: 90  },
      { op: 'Ashley',  x: 30,  y: 325, deg: 270 },
      { op: 'Cassidy', x: 80,  y: 350, deg: 315 },
    ],
    event: 'entry',
  },
  // 22
  {
    title: 'Manny calls — Closed door left',
    callout: 'Manny: "Closed door left."',
    teaching: 'Point bumps past the second closed door (left side). Mike moves with Manny — sets on door, doorknob side.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 40,  y: 390 },
      Mike:    { x: 55,  y: 375 },
      Ian:     { x: 270, y: 120 },
      Austin:  { x: 225, y: 445 },
      Ashley:  { x: 30,  y: 325 },
      Dylan:   { x: 300, y: 445 },
      Cassidy: { x: 80,  y: 350 },
    },
    angles: [
      { op: 'Manny', x: 40, y: 390, deg: 90 },
      { op: 'Mike',  x: 55, y: 375, deg: 0  },
    ],
    event: null,
  },
  // 23
  {
    title: 'Mike opens — bang — Room 2',
    callout: '— BANG — Room 2',
    teaching: 'Mike on doorknob side. Ian on hinge side. Mike opens and deploys bang.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 40,  y: 410 },
      Mike:    { x: 80,  y: 378 },
      Ian:     { x: 15,  y: 378 },
      Austin:  { x: 225, y: 445 },
      Ashley:  { x: 30,  y: 325 },
      Dylan:   { x: 300, y: 445 },
      Cassidy: { x: 80,  y: 350 },
    },
    angles: [
      { op: 'Manny', x: 40, y: 410, deg: 90 },
    ],
    event: 'bang',
  },
  // 24
  {
    title: 'Ian and Mike detail Room 2',
    callout: '',
    teaching: 'Ian enters first. Mike follows. They detail Room 2.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 40,  y: 430 },
      Mike:    { x: 70,  y: 420 },
      Ian:     { x: 30,  y: 420 },
      Austin:  { x: 225, y: 445 },
      Ashley:  { x: 30,  y: 325 },
      Dylan:   { x: 300, y: 445 },
      Cassidy: { x: 80,  y: 350 },
    },
    angles: [
      { op: 'Manny', x: 40, y: 430, deg: 90  },
      { op: 'Ian',   x: 30, y: 420, deg: 270 },
      { op: 'Mike',  x: 70, y: 420, deg: 315 },
    ],
    event: 'entry',
  },
  // 25
  {
    title: 'Manny calls — Last room, open door left',
    callout: 'Manny: "Last room, open door left."',
    teaching: 'Open door means point does NOT bump past. Manny stops short and hugs the wall.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 35,  y: 455 },
      Mike:    { x: 70,  y: 420 },
      Ian:     { x: 30,  y: 420 },
      Austin:  { x: 55,  y: 455 },
      Ashley:  { x: 30,  y: 325 },
      Dylan:   { x: 300, y: 445 },
      Cassidy: { x: 80,  y: 350 },
    },
    angles: [
      { op: 'Manny',  x: 35, y: 455, deg: 90 },
      { op: 'Austin', x: 55, y: 455, deg: 90 },
    ],
    event: null,
  },
  // 26
  {
    title: 'Austin deploys bang — last room',
    callout: '— BANG — Last Room',
    teaching: 'Austin throws the distraction device into the last room before entry.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 35,  y: 455 },
      Mike:    { x: 70,  y: 420 },
      Ian:     { x: 30,  y: 420 },
      Austin:  { x: 55,  y: 460 },
      Ashley:  { x: 30,  y: 325 },
      Dylan:   { x: 300, y: 445 },
      Cassidy: { x: 80,  y: 350 },
    },
    angles: [
      { op: 'Manny',  x: 35, y: 455, deg: 90 },
    ],
    event: 'bang',
  },
  // 27
  {
    title: 'Manny goes straight — Austin button hooks',
    callout: '',
    teaching: 'Manny goes straight into the last room. Austin button hooks. They detail the final room.',
    positions: {
      Rico:    { x: 20,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 30,  y: 445 },
      Mike:    { x: 70,  y: 420 },
      Ian:     { x: 30,  y: 420 },
      Austin:  { x: 75,  y: 445 },
      Ashley:  { x: 30,  y: 325 },
      Dylan:   { x: 300, y: 445 },
      Cassidy: { x: 80,  y: 350 },
    },
    angles: [
      { op: 'Manny',  x: 30, y: 445, deg: 225 },
      { op: 'Austin', x: 75, y: 445, deg: 315 },
    ],
    event: 'entry',
  },
  // 28 — final confirmation
  {
    title: 'Rico confirms — House is clear',
    callout: 'Rico: "House is clear."',
    teaching: 'All rooms detailed. Rico radios the all-clear. The scenario is complete.',
    positions: {
      Rico:    { x: 55,  y: 105 },
      Chris:   { x: 55,  y: 75  },
      Mags:    { x: 55,  y: 135 },
      Manny:   { x: 30,  y: 445 },
      Mike:    { x: 70,  y: 420 },
      Ian:     { x: 30,  y: 420 },
      Austin:  { x: 75,  y: 445 },
      Ashley:  { x: 30,  y: 325 },
      Dylan:   { x: 300, y: 445 },
      Cassidy: { x: 80,  y: 350 },
    },
    angles: [],
    event: null,
  },
];
